
# Gem::Specification for Valuation-0.0.1
# Originally generated by Echoe

--- !ruby/object:Gem::Specification 
name: valuation
version: !ruby/object:Gem::Version 
  version: 0.0.1
platform: ruby
authors: 
- Tim Kofol
autorequire: 
bindir: bin

date: 2008-10-12 00:00:00 -04:00
default_executable: 
dependencies: 
- !ruby/object:Gem::Dependency 
  name: echoe
  type: :development
  version_requirement: 
  version_requirements: !ruby/object:Gem::Requirement 
    requirements: 
    - - ">="
      - !ruby/object:Gem::Version 
        version: "0"
    version: 
description: A Ruby Gem For Corporate Finance.
email: tkofol@gmail.com
executables: []

extensions: []

extra_rdoc_files: 
- lib/valuation/cash_flows.rb
- lib/valuation/core_ext.rb
- lib/valuation/interest_rate.rb
- lib/valuation.rb
- README.textile
files: 
- History.txt
- lib/valuation/cash_flows.rb
- lib/valuation/core_ext.rb
- lib/valuation/interest_rate.rb
- lib/valuation.rb
- License.txt
- Manifest
- Rakefile
- README.textile
- test/test_cash_flows.rb
- test/test_helper.rb
- test/test_interest_rate.rb
- test/test_valuation.rb
- valuation.gemspec
has_rdoc: true
homepage: ""
post_install_message: 
rdoc_options: 
- --line-numbers
- --inline-source
- --title
- Valuation
- --main
- README.textile
require_paths: 
- lib
required_ruby_version: !ruby/object:Gem::Requirement 
  requirements: 
  - - ">="
    - !ruby/object:Gem::Version 
      version: "0"
  version: 
required_rubygems_version: !ruby/object:Gem::Requirement 
  requirements: 
  - - ">="
    - !ruby/object:Gem::Version 
      version: "1.2"
  version: 
requirements: []

rubyforge_project: valuation
rubygems_version: 1.2.0
specification_version: 2
summary: A Ruby Gem For Corporate Finance.
test_files: 
- test/test_cash_flows.rb
- test/test_helper.rb
- test/test_interest_rate.rb
- test/test_valuation.rb
